### ISSUE TITLE
Emoji-picker pushing error during the production build time (ionic cordova build android --prod)

### ISSUE THREAD

**Issue by krishna022** [danielehrhardt/ionic3-emoji-picker#10]
`[16:22:15]  ionic-app-script task: "build" 
[16:22:15]  Error: ./src/app/app.module.ngfactory.js Module not found: Error: Can't resolve 
            '../../node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory' in 
            '/Users/krishnamohan/Desktop/Footsy-Mobile-App/src/app' resolve 
            '../../node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory' in 
            '/Users/krishnamohan/Desktop/Footsy-Mobile-App/src/app' using description file: 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/package.json (relative path: ./src/app) Field 'browser' 
            doesn't contain a valid alias configuration after using description file: 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/package.json (relative path: ./src/app) using description 
            file: 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/package.json 
            (relative path: ./components/emoji-picker.component.ngfactory) no extension Field 'browser' doesn't contain 
            a valid alias configuration 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory
            doesn't exist .ts Field 'browser' doesn't contain a valid alias configuration 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.ts
            doesn't exist .js Field 'browser' doesn't contain a valid alias configuration 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.js
            doesn't exist .json Field 'browser' doesn't contain a valid alias configuration 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.json
            doesn't exist as directory 
            /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory
            doesn't exist 
            [/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory]
            [/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.ts]
            [/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.js]
            [/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.json]
            [/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory]
            @ ./src/app/app.module.ngfactory.js 20:0-121 @ ./src/app/main.ts 
Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory' in '/Users/krishnamohan/Desktop/Footsy-Mobile-App/src/app'
resolve '../../node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory' in '/Users/krishnamohan/Desktop/Footsy-Mobile-App/src/app'
  using description file: /Users/krishnamohan/Desktop/Footsy-Mobile-App/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/krishnamohan/Desktop/Footsy-Mobile-App/package.json (relative path: ./src/app)
    using description file: /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/package.json (relative path: ./components/emoji-picker.component.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.json doesn't exist
      as directory
        /Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory doesn't exist
[/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory]
[/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.ts]
[/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.js]
[/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory.json]
[/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic-tools/emoji-picker/lib-dist/components/emoji-picker.component.ngfactory]
 @ ./src/app/app.module.ngfactory.js 20:0-121
 @ ./src/app/main.ts
    at new BuildError (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err `(/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/Compiler.js:262:10)`
    at applyPluginsAsyncSeries1.err (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/krishnamohan/Desktop/Footsy-Mobile-App/node_modules/webpack/lib/Compiler.js:365:9)
`

When I am removing the Emoji-Picker then there is no any error.
And in the normal build emoji is working fine.

**Comment by ahkohd** [comment]
Yeah, this is a know issue. This library is not compatible with newer angular version  beacause of some breaking changes so I upgraded it. Use https://www.npmjs.com/package/ngx-emoji-picker instead or
https://www.npmjs.com/package/ngx-emoj
